version: '2'
services:
  middleware-app:
    image: middleware
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://middleware-postgresql:5432/middleware
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  middleware-postgresql:
    extends:
      file: postgresql.yml
      service: middleware-postgresql
